### PR TITLE
Drop pify

### PR DESCRIPTION
**Pull request by sibiraj-s**
Drop `pify` in favour of `util.promisify`

Following up from https://github.com/forwardemail/email-templates/pull/409.

### CODE REVIEW

**Comment by sibiraj-s** [comment]
@niftylettuce. tracking `email-templates` package's dependencies and trying to reduce its install size. 

Since node 8 is no longer in LTS. If it is okay drop that and by looking at the code we no longer will need babel. and also we can update someother dependencies as well. which can potentially reduce the size of the package. If you are okay with doing a major release I can make changes here as well as to the `email-templates` package?

Thoughts?

**Comment by niftylettuce** [comment]
yes you can drop Node 8 @sibiraj-s

**Comment by sibiraj-s** [comment]
@niftylettuce I have made the changes. didn't update few things since there are other PR's around that. I will do a total dependency bump PR once other PR's related to dependencies are merged.

**Comment by niftylettuce** [comment]
v3.0.0 released https://github.com/forwardemail/preview-email/releases/tag/v3.0.0

**Comment by sibiraj-s** [comment]
@niftylettuce with 3.0 there is a 3MB drop in install size. 

Screenshot 2020-11-23 at 8 34 42 AM

**Comment by niftylettuce** [comment]
thank you @sibiraj-s - I'm also updating this in `email-templates` right now and bumping that to v8.0.0

**Comment by sibiraj-s** [comment]
Great.

**Pull request merged**
